name: Update Fund Data

on:
  schedule:
    - cron: '0 1 * * 1-5'  # UTC时间1:00 AM (北京时间9:00 AM)，周一至周五
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install akshare pandas jinja2
          
      - name: Update fund data
        run: python generate.py
        
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add docs/index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Update fund data: $(date +'%Y-%m-%d')"
          git push